### ISSUE TITLE
Game crashes on saving/loading on Linux

### ISSUE THREAD

**Issue by Leebre** [stohrendorf/CroftEngine#257] opened 2022-08-14 11:39 UTC
Hi, I have tried playing TR1 with CroftEngine in Linux (Arch variant) on an x86 desktop PC. The game seems to run ok; however it is crashing on saving/loading, which renders it unplayable. I will be happy to post errors/logs, if it would help.

The game also seems to crash when Lara dies, but I'm not sure if this is linked to the save/load crash.

**Comment by stohrendorf** [comment] 2022-08-14 16:15
A log after the crash would be good, it could provide insights about what happened.

**Comment by Leebre** [comment] 2022-08-15 00:43
> A log after the crash would be good, it could provide insights about what happened.

Ok. I will attach the most recent log file after a crash on trying to save on the first level. I will also attach the terminal messages that were printed during the crash as well. It seems similar to the log file, but has an extra couple of lines at the end.

[croftengine.log](https://github.com/stohrendorf/CroftEngine/files/9334446/croftengine.log)
[crash_error.log](https://github.com/stohrendorf/CroftEngine/files/9334447/crash_error.log)

**Comment by stohrendorf** [comment] 2022-08-17 17:47
I am unable to reproduce this. The logs aren't really helpful in this case. It would be really helpful if you could attach a debugger and give me a stacktrace, because I don't know where the crash appears. When saving/loading, the engine uses standard mechanisms to save/load a file that's culture-independent, and that works fine as far as I can tell. When setting the locale to `en_US.UTF8`, the engine properly defaults to a non-translated version.

**Comment by stohrendorf** [comment] 2022-11-30 18:09
Closing this as it's probably some issue with the host system itself, and noone else has reported something similar on any platform. Feel free to re-open if you have more information.

**Closed by stohrendorf** 2022-11-30 18:09 UTC
